### ISSUE TITLE
Option for adding subtitles file in Player

### ISSUE THREAD

**Issue by gurpreet-singh135** [akumar98394/sync-play666#1]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
There must an option to upload subtitles file to online player

**Additional context**
Most of the online streaming services like Netflix, Prime etc have option to display subtitles, so there must be option to add subtitles.

**Comment by 0mega28** [comment]
Gurpreet Singh thanks for your review, your issue has been resolved.
